spring.application.name=github-share-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/githubshare
spring.datasource.username=githubuser
spring.datasource.password=githubpass
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# GitHub OAuth
github.client.id=Ov23livJiseiVAkqNiyD
github.client.secret=98c4e69f50649121fd52cd5f430da7ff02247887
github.redirect.uri=http://localhost:8080/api/auth/github/callback

##encrytion
app.encryption.secret=0123456789123456

#view url
app.viewer.base-url=http://localhost:4200/access/





