spring.application.name=github-share-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/githubshare
spring.datasource.username=githubuser
spring.datasource.password=githubpass
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

